version: '3.8'

services:
  bff:
    build: .
    container_name: myqx-bff
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-default-key-for-dev-only}
      - ALLOWED_HOSTS=localhost,127.0.0.1,10.0.2.2
      - CORS_ALLOW_ALL_ORIGINS=True
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - USERS_SERVICE_URL=${USERS_SERVICE_URL:-http://localhost:8001/api}
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - myqx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Puedes añadir más servicios aquí, como una base de datos
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=myqx
  #   networks:
  #     - myqx-network

networks:
  myqx-network:
    driver: bridge

volumes:
  static_volume:
  # postgres_data: # Descomenta si usas PostgreSQL