@startuml Index

!include style-config.puml

title Índex de Diagrames d'Arquitectura - Myqx-BFF

rectangle "Estructura General" as General #CLIENT_COLOR {
  text "estructura-general.puml"
}

together {
  rectangle "Vistes i Processament" as Vistes #VIEW_COLOR {
    text "vistes-i-processament.puml"
  }
  
  rectangle "Controladors i Vistes" as Controladors #CONTROLLER_COLOR {
    text "controladors-i-vistes.puml"
  }
}

together {
  rectangle "Serveis i Interfícies" as Serveis #SERVICE_COLOR {
    text "serveis-i-interficies.puml"
  }
  
  rectangle "Repositoris, DTOs i Models" as Repositoris #REPOSITORY_COLOR {
    text "repositoris-dtos-models.puml"
  }
}

rectangle "Utils i Configuració" as Utils #UTILS_COLOR {
  text "utils-i-configuracio.puml"
}

rectangle "Flux Complet de Peticions" as Flux #INTERFACE_COLOR {
  text "flux-peticions.puml"
}

General -down-> Vistes
General -down-> Controladors
General -down-> Serveis
General -down-> Repositoris
General -down-> Utils
General -down-> Flux

note right
  <b>Diagrames d'Arquitectura Myqx-BFF</b>
  
  Aquest índex conté els enllaços a tots els diagrames
  d'arquitectura disponibles per al projecte Myqx-BFF.
  
  Actualitzat: 14 de Maig, 2025
end note

@enduml
